# Imagen oficial de PHP con Apache
FROM php:8.2-apache

# Instalar extensiones necesarias
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

# Copia tu código al contenedor
COPY . /var/www/html/

# Permisos adecuados
RUN chown -R www-data:www-data /var/www/html

# Habilitar mod_rewrite si es necesario (para frameworks)
RUN a2enmod rewrite

# Exponer el puerto que Apache utiliza
EXPOSE 80
