# Imagen base
FROM php:8.2-apache

# Instalar extensiones necesarias
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copiar todo el contenido del backend al servidor apache
COPY . /var/www/html/

# Dar permisos
RUN chown -R www-data:www-data /var/www/html

# Activar mod_rewrite (si es necesario para rutas amigables)
RUN a2enmod rewrite

# Exponer el puerto
EXPOSE 80
